[build]
  command = "npm run build"
  publish = "."
  functions = "functions"

[functions]
  external_node_modules = ["express", "socket.io"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 